global:
  domain: <DOMAIN_NAME>
  imagePullSecret: {}
srv:
  bindings:
    destinations:
      fromSecret: <RELEASE_NAME_OF_KYMAAPP>-srv-destinations
    messaging:
      fromSecret: <RELEASE_NAME_OF_KYMAAPP>-srv-messaging
  image:
    repository: <DOCKER_ACCOUNT>/kymamock
    tag: latest
  resources:
    limits:
      cpu: 3000m
      ephemeral-storage: 1G
      memory: 1G
    requests:
      cpu: 3000m
      ephemeral-storage: 1G
      memory: 1G
  health_check:
    liveness:
      path: /
    readiness:
      path: /
