global:
  domain: <DOMAIN_NAME>
  imagePullSecret: {}
srv:
  bindings:
    destinations:
      fromSecret: <RELEASE_NAME_OF_KYMAAPP>-srv-destination
    messaging:
      fromSecret: <RELEASE_NAME_OF_KYMAAPP>-srv-messaging
  image:
    repository: <DOCKER_ACCOUNT>/kymamock
    tag: latest
  resources:
    limits:
      cpu: 500m
      ephemeral-storage: 500M
      memory: 500M
    requests:
      cpu: 500m
      ephemeral-storage: 500M
      memory: 500M
  health_check:
    liveness:
      path: /
    readiness:
      path: /
